version: "3.9"
services:
  db:
    image: postgres:15.1-bullseye
    secrets:
      - postgres-password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - POSTGRES_DB=corporate-emissions
      - PGDATA=/var/lib/postgresql/data/emissionspgdata
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  server:
    depends_on:
      - db
    build:
      context: ./server
      target: development
    secrets:
      - postgres-password
    environment:
      - EMISSIONS_DB_PASSWORD_FILE=/run/secrets/postgres-password
    ports:
      - "5000:5000"
  client:
    depends_on:
      - server
    build:
      context: ./client
      target: development
    ports:
      - "3000:3000"
    volumes:
      - "./client/src:/client/src"

secrets:
  postgres-password:
    file: ./.secrets/postgres_password.txt
