version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    secrets:
      - google_application_credentials
    env_file:
      - .secrets/db.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_application_credentials

secrets:
  google_application_credentials:
    file: .secrets/delta-timer-368701-acae2bbc9838.json
