version: "3.9"
services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ~/certbot/www/:/var/www/certbot/:rw
      - ~/certbot/conf/:/etc/letsencrypt/:rw
  db:
    image: postgres:15.1-bullseye
    environment:
      - POSTGRES_PASSWORD=${EMISSIONS_DB_PASSWORD}
      - POSTGRES_DB=corporate-emissions
      - PGDATA=/var/lib/postgresql/data/emissionspgdata
    volumes:
      - "~/pgdata:/var/lib/postgresql/data"
  server:
    depends_on:
      - db
    image: rcraigfiedorek/emissions-bot:server
    build:
      context: ./server
      target: production
    environment:
      - EMISSIONS_DB_PASSWORD=${EMISSIONS_DB_PASSWORD}
  client:
    depends_on:
      - server
    build:
      context: ./client
      target: production
    image: rcraigfiedorek/emissions-bot:client
    volumes:
      - ~/certbot/www:/var/www/certbot:ro
      - ~/certbot/conf:/etc/nginx/ssl:ro
    ports:
      - "80:80"
