version: "3.9"
services:
  server:
    build: ./server
    secrets:
      - google_application_credentials
    env_file:
      - .secrets/db.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_application_credentials
  client:
    depends_on:
      - server
    build: ./client
    ports:
      - "3000:80"

secrets:
  google_application_credentials:
    file: .secrets/delta-timer-368701-acae2bbc9838.json
