version: "3.9"
services:
  server:
    build: ../server
    image: rcraigfiedorek/emissions-bot:server
    secrets:
      - google_application_credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_application_credentials
  client:
    depends_on:
      - server
    build: ../client
    image: rcraigfiedorek/emissions-bot:client
    ports:
      - "3000:80"

secrets:
  google_application_credentials:
    file: ../.secrets/delta-timer-368701-acae2bbc9838.json
